name: Python Cache Demo

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - main

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Cache pip dependencies
      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-62b476e

      # Step 4: Prime cache step (prints hit/miss)
      - name: prime-cache-62b476e
        run: |
          if [ "${{ steps.cache-step.outputs.cache-hit }}" == 'true' ]; then
            echo "Cache hit ✅"
          else
            echo "Cache miss ❌"
          fi

      # Step 5: Install dependencies
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found, skipping pip install."
          fi
